services:
    Literato\Bundle\PaymentBundle\Gateway\PaymentGatewayInterface: '@literato_payment.gateway'

    literato_payment.gateway:
        class: Literato\Bundle\PaymentBundle\Gateway\PaymentGateway
        arguments: [ '@event_dispatcher' ]

    literato_payment.cryptomus_gateway:
        class: Literato\Bundle\PaymentBundle\Gateway\CryptomusPaymentGateway
        arguments: ~